docs(mt): baidu machine translation
tolgee/documentation pull request #371
Opened 2023-03-10 07:27 UTC by wfjsw

2023-03-10 08:10 UTC, JanCizmar approved these changes

2023-03-14 09:07 UTC, Martin005 requested changes

2023-03-14 09:10 UTC, wfjsw commented on platform/self_hosting/configuration.mdx
> +See [Manage Terms](https://fanyi-api.baidu.com/manage/term). (default: `false`)
It is a link to the management portal. Requires login.

2023-03-14 09:11 UTC, Martin005 commented on platform/self_hosting/configuration.mdx
> +See [Manage Terms](https://fanyi-api.baidu.com/manage/term). (default: `false`)
Ah, I see 👍 Then please add information that a user should be logged in to be able to access this link.

2023-03-14 09:46 UTC, JanCizmar approved these changes

2023-03-14 10:03 UTC, Martin005 approved these changes

2023-03-14 10:07 UTC, merged