feat: Figma plugin LP, docs and blog post
tolgee/documentation pull request #380
Opened 2023-03-16 12:16 UTC by Martin005

This PR adds Landing Page, docs and a blog post for our Figma plugin.
I have also fixed a few issues in one blog post and one docs article.

2023-03-16 13:01 UTC, marketachalupnikova requested changes

2023-03-16 13:01 UTC, marketachalupnikova commented on src/pages/integrations/figma.tsx
> +          content="Connect your Figma designs with Tolgee. This integration will make the process of localizing your designs faster, easier, and more efficient."
meta description should be a bit longer. e.g. you can add: Connect your Figma designs with Tolgee localization platform

2023-03-16 13:26 UTC, Martin005 commented
@marketachalupnikova Thank you! 🙂

2023-03-17 08:59 UTC, stepan662 approved these changes

2023-03-17 09:38 UTC, merged