feat: Platform docs update
tolgee/documentation pull request #391
Opened 2023-04-03 12:27 UTC by Martin005

This PR rebuilds the Platform documentation from the ground up and makes the documentation more structural.

I didn't include the `Members` project page as the [Granular permissions](https://github.com/tolgee/tolgee-platform/issues/1336) will be finished shortly and will change completely how the permissions work. After the Granular permisisons are done, I will create a separate PR describing this new feature.

2023-04-04 13:48 UTC, marketachalupnikova requested changes

2023-04-04 13:48 UTC, marketachalupnikova commented on platform/getting_started/translation_content.mdx
> +title: Translation Content
I am not sure about the title Translation Content. How about Translation data?

2023-04-04 13:48 UTC, marketachalupnikova commented on platform/self_hosting/getting_started.mdx
> +Pricing for the self-hosted version is different from the cloud version. You can find the pricing [here](/pricing/self-hosted).
I'd add this part once self-hosting pricing is released. Also, I'd describe more details about free self-hosting and paid version

2023-04-06 09:19 UTC, stepan662 approved these changes
Cool :) Just some comments about the namespaces, I got one a bit annoyed customer on chatwoot - he started using namespaces for everything and then it was very messy.

2023-04-06 09:19 UTC, stepan662 commented on static/img/docs/platform/export_select_namespaces.png
Not sure if this is a best example.
 1. namespaces by platform doesn't make much sense for me as that would lead to many duplicities
  - better examples would probably be by some application sections like 'common', 'main', 'billing' (this would make sense e.g. for Tolgee when Billing is in separate repository and the translations are not needed when self-hosting).
 2. I would encourage users to name all the namespaces when they are using them (and not use <none>) in this case

2023-04-06 09:19 UTC, stepan662 commented on platform/integrations/about_integrations.mdx
> +![img](/img/docs/platform/project_menu_integrate.png)
This is a screenshot from old design, I guess it can be removed, becuse from the following screenshot it's pretty clear.

2023-04-06 12:02 UTC, merged